### ISSUE TITLE
Changes to Southern Pines

### ISSUE THREAD

**Issue by allen121** [golf-clash-notebook/golf-clash-notebook.github.io#136]
Some of the holes in Southern Pines in Tour 11 have been renumbered.

**Comment by cranst0n** [comment]
Thanks! I believe that they've done the same to Santa Ventura and Glenmonarch Estate. I'll be updating as soon as I can figure out which holes are which. Any contributions towards this are more than welcome.

**Comment by glarcina** [comment]
This what I had found around a month ago for Southern Pines when I was doing tour 6:

### [GCN.io] - > [In game]
* 4 -> 3
* 3 -> 8
* 7 -> 1
* 6 -> 5
* 9 -> 4
* 1 -> 7

I guess 2 was still 2.  

Hope this helps

**Comment by cranst0n** [comment]
Thanks @glarcina. I've got an ongoing translation to the new numbering scheme I'll be using [here](https://github.com/golf-clash-notebook/golf-clash-notebook.github.io/blob/dev/HoleNumberTranslations.md). I still need to add the new Milano holes. The scheme matches the numbers you see in the replays in the the game.
