### ISSUE TITLE
Proposal to Create a Privacy Policy for Golf Clash Notebook 

### ISSUE THREAD

**Issue by frankremmy** [golf-clash-notebook/golf-clash-notebook.github.io#149]
Hello, 

I have been using your project for a while and must say it's really amazing. Also, I've been getting myself acquainted with the project and found out something essential is missing out: Privacy Policy. 

Well, users will be finding it unsecured to sign in to the site with their Facebook, Google or Twitter account. So they often read the About Us, Privacy Policy, Terms of Services, Homepage, etc. 

I am a veteran copywriter and would love to contribute to your project, starting with a Privacy Policy. The question is: Would you review, correct and merge it to your repository when it is done so as it'll show on the site? If so, let me know so I can get started as soon as possible. 

Thanks.

**Comment by cranst0n** [comment]
Hi! Thanks for raising this point. I actually already have a Privacy Policy and Terms & Conditions drawn up but the links on the site are broken. I've submitted a PR to fix the broken links but in the meantime you can look over the existing [Privacy Policy](https://github.com/golf-clash-notebook/golf-clash-notebook.github.io/blob/dev/modules/site/src/main/tut/privacy.md) and [Terms and Conditions](https://github.com/golf-clash-notebook/golf-clash-notebook.github.io/blob/dev/modules/site/src/main/tut/terms.md).

This is most definitely ***not*** my area of expertise so if you have any input on what's there please feel free to raise any issues, suggestions, etc.

**Comment by frankremmy** [comment]
Wow. I've gone through the copies and they're OK to be used. I only thought the site was lacking these. 
The Privacy Policy and Terms and Conditions are cool.
