### ISSUE TITLE
Wind Chart Error when looking at Malibu Sand Wedge

### ISSUE THREAD

**Issue by Joruus20** [golf-clash-notebook/golf-clash-notebook.github.io#162]
Hi, when looking at the Mailbu sand wedge under the Clubs tab, I clicked on the Wind chart and selected Level 8, The chart states each ring is worth 1.80 wind at 100 accuracy.  When looking at the wind accuracy detailed guide chart a club that is at 100 should be 1.00 per ring.  Currently on the Malibu it reads 1.80 per ring at Level 8 instead of 1.00.  I think there are other clubs with the same issue.  I will report the issues as I find them.

Thanks,
Joe

**Comment by cranst0n** [comment]
Rough irons and sand wedges don't follow the same formula in terms of accuracy as other club categories. The accuracy chart you're referring to holds for all other club categories, generally speaking.

**Comment by Joruus20** [comment]
Thanks for taking the time for clearing that up.
