### ISSUE TITLE
Club Ranker

### ISSUE THREAD

**Issue by jeffy47** [golf-clash-notebook/golf-clash-notebook.github.io#164]
First off I'd like to say that golfclashnotebook is an amazing website that has helped me out a ton! One way the website could be improved is if a description/explanation of how the club ranker works. Specifically, how the sliders work/affect the rankings and stats.

**Comment by cranst0n** [comment]
Thanks for the suggestion @jeffy47! Would you like to take a first cut at writing a short paragraph to add to the page? I'd be happy to merge it for you (giving credit of course).

**Comment by jeffy47** [comment]
I would, but I do not understand how the sliders work. (It would help me too haha)

**Comment by cranst0n** [comment]
Ah okay then. I'll see if I can throw something together. For now, a quick explanation is that as you slide each attribute (power, accuracy, etc.) to the right, it weights that attribute higher. So in theory if you slid every slider to 0 and top spin to 100, the Big Topper would be the highest ranked driver. If you only valued accuracy, then the Quarterback and Rock would be ranked highest.

**Comment by glarcina** [comment]
Heck I'd just put that example above on the page somehow. Cleared that right up for me!
