### ISSUE TITLE
Hole #s are almost always wrong

### ISSUE THREAD

**Issue by BrewmeisterP** [golf-clash-notebook/golf-clash-notebook.github.io#190]
It takes a long time to find the hole while playing becauue your hole numbers are so often wrong.

**Comment by cranst0n** [comment]
@BrewmeisterP This is a known issue (#136). At some point I'll be adopting the (3, 3b, 3c, 4 4b, etc.) scheme since Playdemic changes the holes numbers constantly.

**Comment by BrewmeisterP** [comment]
I didn’t know that.  Thanks.

**Comment by BrewmeisterP** [comment]
An easier, short-term perhaps, solution would be to list the holes with par 3 on top, par 4 on second row, and par 5 on bottom.  You can easily find the hole by the layout if you can quickly find the par.  As it is you end up having to scan all the images and/or find the par 5 holes, e.g.

 

PMR

**Comment by cranst0n** [comment]
This is an issue that probably won't be fixed. PD constantly changes their hole numbers and it's not realistic for me to stay on top of it. The replay names (4C, 3B, 5, etc.) are permanent however so there's a small silver lining there I suppose.
