### ISSUE TITLE
Simple mode

### ISSUE THREAD

**Issue by gripped** [golf-clash-notebook/golf-clash-notebook.github.io#213]
https://github.com/golf-clash-notebook/golf-clash-notebook.github.io/commit/86a2742016fdccf518e406a9e04640648b92e8bd removed simple mode.
Shame as I prefer it. Shows how long it is since I upgraded my clubs :)

Just started a new account and went to create a new chart. I'd rather see "2" than "2.02" etc.
Is there any chance of resurrecting it ? Was it doing any harm ?

Thanks for all the hard work.
"Good Luck!"

**Comment by cranst0n** [comment]
@gripped Yes it's on the TODO list. There have been quite a few requests to bring it back. Just haven't found the time to do it just yet.

**Comment by gripped** [comment]
Top Bombing :)
