### ISSUE TITLE
Personal Hole Notes not showing

### ISSUE THREAD

**Issue by sdub999** [golf-clash-notebook/golf-clash-notebook.github.io#214]
the personal hole notes do not seem to be displaying all the time.  It seems to be somewhat random when they are visible versus when they do not show up.  I am using Chrome and logging in with a Google Account.  The notes seem to be saving as when I open on my mobile device they appear, but they are not coming up on the same browser that I created the notes from.

**Comment by cranst0n** [comment]
I haven't been able to recreate the issue yet but will investigate later when I have some more time. Let me know if you have any more insight into recreating the problem!
