### ISSUE TITLE
Club Oceania Hole Links are Wrong

### ISSUE THREAD

**Issue by byarbyar** [golf-clash-notebook/golf-clash-notebook.github.io#221]
Clicking on a hold on the Club Oceania tournament loads the wrong hole.

**Comment by cranst0n** [comment]
Can you be a little more specific? I can't see any obvious issues but maybe you're running into a more subtle one.

**Comment by byarbyar** [comment]
The hole pictures are correct but the hole headers are wrong.

 

Oceania



 

Origin

**Comment by UnderDogg** [comment]
@byarbyar the images didn't show up in the issue, can you reupload them in the github issue?

**Comment by cranst0n** [comment]
Closing as I can't see any issues but feel free to reopen it if I'm missing something.
