### ISSUE TITLE
build/compile errors

### ISSUE THREAD

**Issue by elubin** [golf-clash-notebook/golf-clash-notebook.github.io#287]
thought i would download and compile and take a look at adding some features... i'm on windows 10

downloaded scala and got the following on the "site/makeMicrosite" command

```
[info] Done compiling.
[info] Done compiling.
[info] Done compiling.
[info] Compiling 29 Scala sources to C:\src\golf-clash-notebook.github.io\modules\site\target\scala-2.12\classes ...
[error] C:\src\golf-clash-notebook.github.io\modules\site\src\main\scala\golfclash\notebook\page\crowdcaddy.scala:39:29: not found: type Hole
[error]   case class Scenario(hole: Hole, optionA: ClubLevel, optionB: ClubLevel) {
[error]                             ^
[error] C:\src\golf-clash-notebook.github.io\modules\site\src\main\scala\golfclash\notebook\page\crowdcaddy.scala:165:24: not found: type Hole
[error]   def randomHole: Task[Hole] = {
[error]                        ^
[error] C:\src\golf-clash-notebook.github.io\modules\site\src\main\scala\golfclash\notebook\page\crowdcaddy.scala:84:12: dead code following this
[error]       hole <- randomHole
[error]            ^
[error] C:\src\golf-clash-notebook.github.io\modules\site\src\main\scala\golfclash\notebook\page\crowdcaddy.scala:84:7: constructor cannot be inst
[error]  found   : (T1, T2)
```

**Comment by cranst0n** [comment]
Apologies for missing this when you submitted it.

I'm not certain why you're running into this. But the good news is I've actually just removed the code associated with these errors (it was unused anyway), so if you update to the latest head, you shouldn't run into these errors any more.

**Comment by cranst0n** [comment]
Closing for now, but feel free to reopen if you're still having trouble.

**Comment by rtgibbons** [comment]
I believe this issue b/c you have to two files named the same (on case-insensitive systems)

`modules/site/src/main/scala/golfclash/notebook/page/Hole.scala`
`modules/site/src/main/scala/golfclash/notebook/page/hole.scala`

So on macOS and Windows these two files will collide and and only one will persist. 

(If this comment doesn't reopen , i'll just create a new issue)
