### ISSUE TITLE
Grammar errors

### ISSUE THREAD

**Issue by penguin1969** [golf-clash-notebook/golf-clash-notebook.github.io#319]
I am seeing a few grammar errors and thought I would let you know.

On the clubs page, under the drivers. The EM has two errors. You have:
 The distance this club has is unmatched except for those clubs. 

It should be:
The distance this club is unmatched except for those clubs. 

Next, you have a spelling error in the same paragraph.
The word managable should be spelled manageable.

Let me know if you would like for me to proof as much of the site as I can. I have no problem helping out in this capacity.

Penguin

**Comment by cranst0n** [comment]
Sorry for the delayed response but thanks! I'll make the corrections shortly. Feel free to open up other issues with more errors. You can group them up together in 1 issue and I'll address them as I can.
