### ISSUE TITLE
Hole number inaccuracies

### ISSUE THREAD

**Issue by CaptainSora** [golf-clash-notebook/golf-clash-notebook.github.io#367]
There are many hole number inaccuracies for at least the first three tours (I'm only at Tour 3 so can only confirm these ones), I'll update with as many as I can find.

### Tour 3:
Namhae Cliffs:
Hole 8 Part 5 is correct

Sakura Hills:
Hole 4 should be Hole 9, Par 5 is correct, (5B) is correct

**Comment by cranst0n** [comment]
Duplicate #190. Playdemic randomly reassigns holes and it's not a good use of time for me to constantly keep up. Replay names are consistent.
