### ISSUE TITLE
Tour 9 Update - new course

### ISSUE THREAD

**Issue by rtgibbons** [golf-clash-notebook/golf-clash-notebook.github.io#373]
They've removed Juniper Point from Tour 9 and replaced it with Acacia Reserve

I don't see anything on that one, it looks to be a new course.

**Comment by rtgibbons** [comment]
On T4 and T11 also when the time comes, nothing from PD yet.

**Comment by cranst0n** [comment]
Thanks. Closed in 9c034a60a9e1eafcc876bae701a3ca03626ae6b4.
