### ISSUE TITLE
Can I get permission to push a new branch?

### ISSUE THREAD

**Issue by KalamazooJiggs** [golf-clash-notebook/golf-clash-notebook.github.io#403]
I have an update for the site ready locally with the new ShirubaSprings course and WinterMajor2020. Unfortunately I'm unable to push a new branch to GitHub.

I get permission denied when I try to push the new branch up to open a PR.

ERROR: Permission to golf-clash-notebook/golf-clash-notebook.github.io.git denied to KalamazooJiggs.

**Comment by cranst0n** [comment]
No permission is needed to open a PR. You can check out [this guide](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request). Let me know if you have any other questions.

**Comment by KalamazooJiggs** [comment]
Oh I can create fork and create a PR from that. 😁

I’ll do it as soon as I’m back home.
